from django.urls import path
from django.contrib.auth.views import LoginView
from . import views
from django.contrib.auth import views as auth_views


urlpatterns = [
    path('',views.index, name='index'),
    path('about/', views.about, name='about'),
    path('login/', views.login_view, name='login'),
    path('logout/', auth_views.LogoutView.as_view(next_page='login'), name='logout'),
    path('register/', views.register, name='register'),
    path('logout/', views.logout_view, name='logout'),
    path('theme', views.theme, name='theme'),
    path('onlinebanking/', views.online_banking, name='onlinebanking'),
    path('fundtransfer/', views.fund_transfer, name='fundtransfer'),
    path('delete_transaction/<int:transaction_id>/', views.delete_transaction, name='delete_transaction'),
    path('withdraw/', views.withdraw, name='withdraw'),
    path('deposit/', views.deposit, name='deposit'),
    path('billpayment/', views.bill_payment, name='billpayment'),
    path('chatbot/', views.chatbot_page, name='chatbot'),
    path('transaction-data/', views.transaction_data, name='transaction_data'),
    path('forgot_password/', views.forgot_password, name='forgot_password'),
    path('reset-password/<str:uidb64>/<str:token>/', views.reset_password, name='reset_password'),
    path('contact-us/', views.contact_us, name='contact_us'),
    path('request_loan/', views.request_loan, name='request_loan'),
    path('view-loans/', views.view_loans, name='view_loans'),
    path('pay_loan/', views.pay_loan, name='pay_loan'),
    path('payment_success/', views.payment_success, name='payment_success'),
    path('payment_cancelled/', views.payment_cancelled, name='payment_cancelled'),
    path('transactions/', views.filter_transactions, name='filter_transactions'),
    path('download-pdf/', views.download_transaction_history_pdf, name='download_pdf'),
    path('issue-cards/', views.issue_cards, name='issue_cards'),
    path('issue-credit-card/', views.issue_credit_card, name='issue_credit_card'),
    path('payment-success-credit-card/', views.payment_success_credit_card, name='payment_success_credit_card'),
    path('payment-cancelled/', views.payment_cancelled_credit_card, name='payment_cancelled_credit_card'),
    path('issue-debit-card/', views.issue_debit_card, name='issue_debit_card'),
    path('credit-card-requests/', views.view_credit_card_requests, name='view_credit_card_requests'),
    path('debit-card-requests/', views.view_debit_card_requests, name='view_debit_card_requests'),
    path('issue-prepaid-card/', views.issue_prepaid_card, name='issue_prepaid_card'),
    path('payment-success-prepaid-card/', views.payment_success_prepaid_card, name='payment_success_prepaid_card'),
    path('payment-cancelled-prepaid-card/', views.payment_cancelled_prepaid_card, name='payment_cancelled_prepaid_card'),
    path('prepaid-card-requests/', views.view_prepaid_card_requests, name='view_prepaid_card_requests'),
    path('updateuser/', views.update_user, name='update_user'),
    path('deactivate_account/', views.deactivate_account, name='deactivate_account'),
    path('currency-converter/', views.currency_converter, name='currency-converter'),
    path('delete_notification/<int:notification_id>/', views.delete_notification, name='delete_notification'),
    path('clear-notifications/', views.clear_all_notifications, name='clear_notifications'),
    path('pay-with-installments/<int:loan_id>/', views.pay_with_installments, name='pay_with_installments'),
    path('pay-installment/<int:loan_id>/', views.pay_installment, name='pay_installment'),  # Add this line
    path('payment-installment-success/', views.payment_installment_success, name='payment_installment_success'),
    path('payment-installment-cancelled/', views.payment_installment_cancelled, name='payment_installment_cancelled'),
    path('issue-insurance/', views.issue_insurance, name='issue_insurance'),
    path('issue-health-insurance/', views.issue_health_insurance, name='issue_health_insurance'),
    path('payment-success-health-insurance/', views.payment_success_health_insurance, name='payment_success_health_insurance'),
    path('payment-cancelled-health-insurance/', views.payment_cancelled_health_insurance, name='payment_cancelled_health_insurance'),
    path('view-health-insurance-requests/', views.view_health_insurance_requests, name='view_health_insurance_requests'),
    path('issue-car-insurance/', views.issue_car_insurance, name='issue_car_insurance'),
    path('payment-success-car-insurance/', views.payment_success_car_insurance, name='payment_success_car_insurance'),
    path('payment-cancelled-car-insurance/', views.payment_cancelled_car_insurance, name='payment_cancelled_car_insurance'),
    path('view-car-insurance-requests/', views.view_car_insurance_requests, name='view_car_insurance_requests'),
    path('issue-business-insurance/', views.issue_business_insurance, name='issue_business_insurance'),
    path('payment-success-business-insurance/', views.payment_success_business_insurance, name='payment_success_business_insurance'),
    path('payment-cancelled-business-insurance/', views.payment_cancelled_business_insurance, name='payment_cancelled_business_insurance'),
    path('view-business-insurance-requests/', views.view_business_insurance_requests, name='view_business_insurance_requests'),
    path('issue-travel-insurance/', views.issue_travel_insurance, name='issue_travel_insurance'),
    path('payment-success-travel-insurance/', views.payment_success_travel_insurance, name='payment_success_travel_insurance'),
    path('payment-cancelled-travel-insurance/', views.payment_cancelled_travel_insurance, name='payment_cancelled_travel_insurance'),
    path('view-travel-insurance-requests/', views.view_travel_insurance_requests, name='view_travel_insurance_requests'),
    path('check_account/', views.check_account, name='check_account'),

]



