# Generated by Django 4.1.3 on 2024-02-21 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("username", models.CharField(max_length=50, unique=True)),
                ("email", models.EmailField(max_length=100, unique=True)),
                ("phone_number", models.CharField(max_length=15)),
                (
                    "account_type",
                    models.CharField(
                        choices=[
                            ("current", "Current Account"),
                            ("saving", "Savings Account"),
                            ("business", "Business Account"),
                        ],
                        max_length=10,
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Account",
        ),
    ]
