# Generated by Django 4.1.3 on 2024-02-22 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_userprofile"),
    ]

    operations = [
        migrations.DeleteModel(
            name="UserAccount",
        ),
        migrations.AddField(
            model_name="userprofile",
            name="balance",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
