# Generated by Django 4.1.3 on 2024-02-23 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_bill"),
    ]

    operations = []
