# Generated by Django 4.1.3 on 2024-02-25 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0009_alter_transaction_timestamp"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="timestamp",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
