# Generated by Django 4.1.3 on 2024-02-26 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0011_adminmessage"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="adminmessage",
            name="user",
        ),
        migrations.AddField(
            model_name="adminmessage",
            name="email",
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
    ]
