# Generated by Django 4.1.3 on 2024-03-05 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0015_issueloan_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="fund_transfer_limit",
            field=models.DecimalField(decimal_places=2, default=3000, max_digits=10),
        ),
    ]
