# Generated by Django 4.1.3 on 2024-03-05 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0016_userprofile_fund_transfer_limit"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="fund_transfer_limit",
        ),
    ]
