# Generated by Django 4.1.3 on 2024-03-20 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0022_subscriber"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="account_number",
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
