# Generated by Django 4.1.3 on 2024-03-30 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0023_userprofile_account_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="issueloan",
            name="loan_amount",
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
    ]
