# Generated by Django 4.1.3 on 2024-03-30 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0024_alter_issueloan_loan_amount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="issueloan",
            name="loan_amount",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
