# Generated by Django 4.1.3 on 2024-04-03 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0029_remove_notification_userprofile"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="notification",
        ),
        migrations.DeleteModel(
            name="Notification",
        ),
    ]
