# Generated by Django 4.1.3 on 2024-04-03 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0031_notification"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Notification",
        ),
    ]
