# Generated by Django 4.1.3 on 2024-04-05 02:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("accounts", "0035_notification_send_to_all_alter_notification_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="issueloan",
            name="approved",
        ),
        migrations.AddField(
            model_name="issueloan",
            name="interest",
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="notification",
            name="user",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"is_staff": False},
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
