# Generated by Django 4.1.3 on 2024-04-05 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0036_remove_issueloan_approved_issueloan_interest_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="issueloan",
            name="approved",
            field=models.BooleanField(default=False),
        ),
    ]
