# Generated by Django 4.1.3 on 2024-04-06 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0038_remove_issueloan_interest_alter_issueloan_approved"),
    ]

    operations = [
        migrations.AddField(
            model_name="issueloan",
            name="interest_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
