# Generated by Django 4.1.3 on 2024-04-06 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0042_installment_selected"),
    ]

    operations = [
        migrations.AddField(
            model_name="installment",
            name="installment_date",
            field=models.DateField(null=True),
        ),
    ]
